import { Event } from "./types";

export const mtgoWeeklyEvents: Event[] = [
    {
        format: 'Pioneer',
        type: 'MTGO WEEKLY',
        date: 'Monday',
        time: '03:00am',
        location: 'MTGO',
        name: 'Pioneer Preliminary',
        link: 'https://www.mtgo.com/premier-play-2023-prelims-and-format-challenges',
    },
    {
        format: 'Pioneer',
        type: 'MTGO WEEKLY',
        date: 'Monday',
        time: '10:00pm',
        location: 'MTGO',
        name: 'Pioneer Preliminary',
        link: 'https://www.mtgo.com/premier-play-2023-prelims-and-format-challenges',
    },
    {
        format: 'Pioneer',
        type: 'MTGO WEEKLY',
        date: 'Tuesday',
        time: '10:00am',
        location: 'MTGO',
        name: 'Pioneer Preliminary',
        link: 'https://www.mtgo.com/premier-play-2023-prelims-and-format-challenges',
    },
    {
        format: 'Pioneer',
        type: 'MTGO WEEKLY',
        date: 'Tuesday',
        time: '06:00pm',
        location: 'MTGO',
        name: 'Pioneer Preliminary',
        link: 'https://www.mtgo.com/premier-play-2023-prelims-and-format-challenges',
    },
    {
        format: 'Pioneer',
        type: 'MTGO WEEKLY',
        date: 'Wednesday',
        time: '02:00pm',
        location: 'MTGO',
        name: 'Pioneer Preliminary',
        link: 'https://www.mtgo.com/premier-play-2023-prelims-and-format-challenges',
    },
    {
        format: 'Pioneer',
        type: 'MTGO WEEKLY',
        date: 'Thursday',
        time: '06:00am',
        location: 'MTGO',
        name: 'Pioneer Preliminary',
        link: 'https://www.mtgo.com/premier-play-2023-prelims-and-format-challenges',
    },
    {
        format: 'Pioneer',
        type: 'MTGO WEEKLY',
        date: 'Friday',
        time: '12:00am',
        location: 'MTGO',
        name: 'Pioneer Preliminary',
        link: 'https://www.mtgo.com/premier-play-2023-prelims-and-format-challenges',
    },
    {
        format: 'Pioneer',
        type: 'MTGO WEEKLY',
        date: 'Friday',
        time: '06:00pm',
        location: 'MTGO',
        name: 'Pioneer Preliminary',
        link: 'https://www.mtgo.com/premier-play-2023-prelims-and-format-challenges',
    },
    {
        format: 'Pioneer',
        type: 'MTGO WEEKLY',
        date: 'Saturday',
        time: '03:00am',
        location: 'MTGO',
        name: 'Pioneer Preliminary',
        link: 'https://www.mtgo.com/premier-play-2023-prelims-and-format-challenges',
    },
    {
        format: 'Pioneer',
        type: 'MTGO WEEKLY',
        date: 'Saturday',
        time: '05:00pm',
        location: 'MTGO',
        name: 'Pioneer Challenge',
        link: 'https://www.mtgo.com/premier-play-2023-prelims-and-format-challenges',
    },
    {
        format: 'Pioneer',
        type: 'MTGO WEEKLY',
        date: 'Sunday',
        time: '09:00am',
        location: 'MTGO',
        name: 'Pioneer Challenge',
        link: 'https://www.mtgo.com/premier-play-2023-prelims-and-format-challenges',
    },
    {
        format: 'Modern',
        type: 'MTGO WEEKLY',
        date: 'Monday',
        time: '10:00am',
        location: 'MTGO',
        name: 'Modern Preliminary',
        link: 'https://www.mtgo.com/premier-play-2023-prelims-and-format-challenges',
    },
    {
        format: 'Modern',
        type: 'MTGO WEEKLY',
        date: 'Monday',
        time: '06:00pm',
        location: 'MTGO',
        name: 'Modern Preliminary',
        link: 'https://www.mtgo.com/premier-play-2023-prelims-and-format-challenges',
    },
    {
        format: 'Modern',
        type: 'MTGO WEEKLY',
        date: 'Tuesday',
        time: '02:00pm',
        location: 'MTGO',
        name: 'Modern Preliminary',
        link: 'https://www.mtgo.com/premier-play-2023-prelims-and-format-challenges',
    },
    {
        format: 'Modern',
        type: 'MTGO WEEKLY',
        date: 'Wednesday',
        time: '06:00pm',
        location: 'MTGO',
        name: 'Modern Preliminary',
        link: 'https://www.mtgo.com/premier-play-2023-prelims-and-format-challenges',
    },
    {
        format: 'Modern',
        type: 'MTGO WEEKLY',
        date: 'Thursday',
        time: '02:00pm',
        location: 'MTGO',
        name: 'Modern Preliminary',
        link: 'https://www.mtgo.com/premier-play-2023-prelims-and-format-challenges',
    },
    {
        format: 'Modern',
        type: 'MTGO WEEKLY',
        date: 'Thursday',
        time: '10:00pm',
        location: 'MTGO',
        name: 'Modern Preliminary',
        link: 'https://www.mtgo.com/premier-play-2023-prelims-and-format-challenges',
    },
    {
        format: 'Modern',
        type: 'MTGO WEEKLY',
        date: 'Friday',
        time: '07:00am',
        location: 'MTGO',
        name: 'Modern Preliminary',
        link: 'https://www.mtgo.com/premier-play-2023-prelims-and-format-challenges',
    },
    {
        format: 'Modern',
        type: 'MTGO WEEKLY',
        date: 'Friday',
        time: '09:00pm',
        location: 'MTGO',
        name: 'Modern Challenge 32',
        link: 'https://www.mtgo.com/premier-play-2023-prelims-and-format-challenges',
    },
    {
        format: 'Modern',
        type: 'MTGO WEEKLY',
        date: 'Saturday',
        time: '11:00am',
        location: 'MTGO',
        name: 'Modern Challenge',
        link: 'https://www.mtgo.com/premier-play-2023-prelims-and-format-challenges',
    },
    {
        format: 'Modern',
        type: 'MTGO WEEKLY',
        date: 'Saturday',
        time: '09:00pm',
        location: 'MTGO',
        name: 'Modern Challenge 32',
        link: 'https://www.mtgo.com/premier-play-2023-prelims-and-format-challenges',
    },
    {
        format: 'Modern',
        type: 'MTGO WEEKLY',
        date: 'Sunday',
        time: '07:00am',
        location: 'MTGO',
        name: 'Modern Challenge',
        link: 'https://www.mtgo.com/premier-play-2023-prelims-and-format-challenges',
    },
    {
        format: 'Pauper',
        type: 'MTGO WEEKLY',
        date: 'Saturday',
        time: '05:00am',
        location: 'MTGO',
        name: 'Pauper Challenge',
        link: 'https://www.mtgo.com/premier-play-2023-prelims-and-format-challenges',
    },
    {
        format: 'Pauper',
        type: 'MTGO WEEKLY',
        date: 'Sunday',
        time: '01:00pm',
        location: 'MTGO',
        name: 'Pauper Challenge',
        link: 'https://www.mtgo.com/premier-play-2023-prelims-and-format-challenges',
    },
]