import { Event } from './types';

export const rcqEvents: Event[] = [
    {
        format: 'Pioneer',
        type: 'RCQ',
        date: '2023-05-06',
        time: '12:00pm',
        location: 'Alternate Universes - East Norriton',
        name: '2-Slot Pioneer Regional Championship Qualifier',
        link: 'https://locator.wizards.com/events/5080234/false',
    },
    {
        format: 'Pioneer',
        type: 'RCQ',
        date: '2023-05-13',
        time: '11:00am',
        location: 'Gregs Games',
        name: '2-Slot Pioneer Regional Championship Qualifier',
        link: 'https://locator.wizards.com/events/5069479/false',
    },
    {
        format: 'Pioneer',
        type: 'RCQ',
        date: '2023-05-13',
        time: '12:00pm',
        location: 'Alternate Universes - Wilmington',
        name: '2-Slot Pioneer Regional Championship Qualifier',
        link: 'https://locator.wizards.com/events/5069479/false',
    },
    {
        format: 'Pioneer',
        type: 'RCQ',
        date: '2023-05-20',
        time: '11:00am',
        location: 'Top Deck Games',
        name: '2-Slot (64 cap) Pioneer Regional Championship Qualifier',
        link: 'https://locator.wizards.com/events/5069479/false',
    },
    {
        format: 'Pioneer',
        type: 'RCQ',
        date: '2023-05-27',
        time: '12:00pm',
        location: 'Alternate Universes - Holmes',
        name: '2-Slot Pioneer Regional Championship Qualifier',
        link: 'https://locator.wizards.com/events/5080241/false',
    },
    {
        format: 'Pioneer',
        type: 'RCQ',
        date: '2023-06-10',
        time: '12:00pm',
        location: 'Alternate Universes - Holmes',
        name: '2-Slot Pioneer Regional Championship Qualifier',
        link: 'https://locator.wizards.com/events/5080248/false',
    },
    {
        format: 'Pioneer',
        type: 'RCQ',
        date: '2023-07-08',
        time: '11:00am',
        location: 'Nova Games',
        name: '2-Slot Pioneer Regional Championship Qualifier',
        link: 'https://locator.wizards.com/events/5166139/false',
    },
    {
        format: 'Pioneer',
        type: 'RCQ',
        date: '2023-07-15',
        time: '11:00am',
        location: 'Gregs Games',
        name: '2-Slot Pioneer Regional Championship Qualifier',
        link: 'https://locator.wizards.com/events/5069514/false',
    },
]