import { Event } from './types';

export const rcqEvents: Event[] = [
    {
        format: 'Modern',
        type: 'RCQ',
        date: '2023-03-18',
        time: '12:00pm',
        location: 'The Bearded Dragon Games',
        name: '2-Slot Modern Regional Championship Qualifier',
        link: 'https://thebeardeddragongames.crystalcommerce.com/Magic%20Events',
    },
    {
        format: 'Modern',
        type: 'RCQ',
        date: '2023-03-25',
        time: '12:00pm',
        location: 'Alternate Universes - Holmes',
        name: '2-Slot Modern Regional Championship Qualifier',
        link: 'https://alternateu.com/special-events/',
    },
    {
        format: 'Modern',
        type: 'RCQ',
        date: '2023-03-26',
        time: '10:00am',
        location: 'The Philly Game Shop',
        name: '2-Slot Modern Regional Championship Qualifier',
        link: 'https://locator.wizards.com/events/4982242/false',
    },
    {
        format: 'Pioneer',
        type: 'RCQ',
        date: '2023-04-01',
        time: '09:00am',
        location: 'Family Fun Hobbies',
        name: '1-Slot Pioneer Regional Championship Qualifier',
        link: 'https://www.shopfamilyfunhobbies.com/magic-the-gathering-regional-championship-qualifie.html',
    },
    {
        format: 'Pioneer',
        type: 'RCQ',
        date: '2023-04-02',
        time: '1:00pm',
        location: 'Saga Concepts',
        name: '1-Slot Pioneer Regional Championship Qualifier',
        link: 'https://locator.wizards.com/events/5008961/false',
    },
    {
        format: 'Pioneer',
        type: 'RCQ',
        date: '2023-05-06',
        time: '12:00pm',
        location: 'Alternate Universes - East Norriton',
        name: '2-Slot Pioneer Regional Championship Qualifier',
        link: 'https://locator.wizards.com/events/5080234/false',
    },
    {
        format: 'Pioneer',
        type: 'RCQ',
        date: '2023-05-13',
        time: '11:00am',
        location: 'Gregs Games',
        name: '2-Slot Pioneer Regional Championship Qualifier',
        link: 'https://locator.wizards.com/events/5069479/false',
    },
    {
        format: 'Pioneer',
        type: 'RCQ',
        date: '2023-05-13',
        time: '12:00pm',
        location: 'Alternate Universes Wilmington',
        name: '2-Slot Pioneer Regional Championship Qualifier',
        link: 'https://locator.wizards.com/events/5069479/false',
    },
    {
        format: 'Pioneer',
        type: 'RCQ',
        date: '2023-05-21',
        time: '12:00pm',
        location: 'Alternate Universes Holmes',
        name: '2-Slot Pioneer Regional Championship Qualifier',
        link: 'https://locator.wizards.com/events/5080241/false',
    },
    {
        format: 'Pioneer',
        type: 'RCQ',
        date: '2023-06-10',
        time: '12:00pm',
        location: 'Alternate Universes Holmes',
        name: '2-Slot Pioneer Regional Championship Qualifier',
        link: 'https://locator.wizards.com/events/5080248/false',
    },
    
]